# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Bacely YoroBi'
tagline:          'Ivorian Entrepreneur'
description:      'I&apos;m <a href="/">Bacely YoroBi</a>, a Internet Strategist and ITC4D Enthusiast<br /><br /> I am from Ivory Coast and I blog about technology , Design , Gaming and entrepreneurship.<br /><br /> I write in English and French.'
url:              http://www.bacelyyorobi.ci

author:
  name:           'Bacely YoroBi'
  url:            https://twitter.com/bacelyy

paginate:         5

image:
  source: public/img
  output: generated
  presets:
    post_excerpt_img:
      attr:
        class: callout
        itemprop: image
      width: 150
    post_content_img:
      attr:
        class: callout
        itemprop: image
      width: 250    
    post_content_img_right:
      attr:
        class: callout_right
        itemprop: image
      width: 250 
# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/yojedesign/bacelyyorobi.github.com